# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kaiven Bugwadia
title: 2024 Computer Science Graduate
email: kbugwadia@gmail.com
website: https://kaivenbugwadia.github.io/resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: -
github_username:  KaivenBugwadia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: -
linkedin_username: kaivenb
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: -
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Screenshot_104.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kaiven and I am a Computer Science major at California State, Monterey Bay in my senior year. 
  I enjoy working with groups to collaborate an achieve the best possible results. I have a passion for building software, 
  finding issues, and helping suggest new features. My goal is to gain professional experience to pursue these passions, 
  while contributing to my team's success.
content:

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Speed Builders
        #link: -
        # link_text: Project Website
        additional_links:
          #- title: -
            icon: fab fa-github 
            # url: -
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Minecraft Mini-game
        description: | # this will include new lines to allow paragraphs
          I am designing a remake of the Minecraft mini-game SpeedBuilders. The game is currently in the bug fixing phase, and is planned to launch within the next 2 months. The vision is to improve the game by adding new unique challenges and cosmetic rewards to keep players interested, while also keeping things fresh with experimental game modes.  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mineplex
        link: Mineplex.com
        # link_text: boringcompany.com
        sub_title: Quality Assurance
        caption: 2020-2023
        quote: >
          Minecraft Game Designing
        description: | # this will include new lines to allow paragraph
          I worked closely with developers to design new Minecraft mini-games as well as updates to various existing mini-games. I learned a lot about the workflow in both projects big and small.
      - layout: left
        title: YMCA
        link: https://www.ymcasv.org/locations/el-camino-ymca
        # link_text: boringcompany.com
        sub_title: Summer Camp Leader
        caption: Summer 2023
        quote: >
          Summer Camp Leader
        description: | # this will include new lines to allow paragraphs
          Created and facilitated activites to help children learn while having fun. I picked up skills in creative problem solving and multitasking. I was offered continued employment after summer for their school year program, but declined due to my college semester starting.
      - layout: left
        title: Microsoft
        link: Microsoft.com
        # link_text: boringcompany.com
        sub_title: Event Coordinator
        caption: Summer 2022
        quote: >
          Planned and hosted a video game tournament in Minecraft.
        description: | # this will include new lines to allow paragraphs
            Lead a team hosting and planning a tournament for the Minecraft mini-game, Speed Builders. With over 100 participants and many volunteers helping, leadership was very important in making everything run smoothly. I created weekly schedules, hosted meetings, and interacted with each participant to gather feedback and improve what I was doing along the way.
      - layout: left
        title: Chick-Fil-A
        link: https://www.chick-fil-a.com/
        # link_text: boringcompany.com
        sub_title: Line Cook
        caption: Summer 2021
        quote: >
          Line cook
        description: | # this will include new lines to allow paragraphs
          While working at Chick-Fil-A I became accustomed to working in a fast paced environment and I learned how to work in a team.    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: California State University, Monterey Bay
        caption: 2020 - 2024
        sub_title: BS Computer Science, 3.7 GPA
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          I completed courses in Data Structures, Software Design, and Mobile Development. I am currently enrolled in Web Development, and Game Development courses. I gained skills in C++, Java, Kotlin, ROOM, and SQL/ite.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In my free time I spend a lot of time with friends as well as taking part in activities such as hiking, cooking/baking, and Hotwheels collecting. I am also an avid video game and movie fan.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
- jekyll-seo-tag
