# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kaiven Bugwadia
title: Student
email: kbugwadia@gmail.com
website: https://kaivenbugwadia.github.io/resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: -
github_username:  KaivenBugwadia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: -
linkedin_username: kaivenb
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: -
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Kaiven and I am a student. I am learning about software designs and want to gain experience by making software. I have gained skills in teamwork and making the dreamwork! 
  I am most skilled in: <mark>C++</mark>, <mark>Java</mark>, and <mark>QA</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Speed Builders
        #link: -
        # link_text: Project Website
        additional_links:
          #- title: -
            icon: fab fa-github
           # url: -
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Minecraft Mini-game
        description: | # this will include new lines to allow paragraphs
          I am designing a remake of the Minecraft mini-game SpeedBuilders, which will launch in the next 2 months. The vision is to improve the game by adding new unique challenges and cosmetic rewards to keep players interested, while also keeping things fresh with experimental game modes.  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        link: Microsoft.com
        # link_text: boringcompany.com
        sub_title: Event Coordinator
        caption: Summer 2022
        quote: >
          Planned and hosted a video game tournament in Minecraft.
        description: | # this will include new lines to allow paragraphs
            Lead a team hosting and planning a tournament for the Minecraft mini-game, Speed Builders. With over 100 participants and many volunteers helping, leadership was very important in making everything run smoothly. I created weekly schedules, hosted meetings, and interacted with each participant to gather feedback and improve what I was doing along the way.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: California State University, Monterey Bay
        caption: 2020 - 2024
        sub_title: BS Computer Science, 3.7 GPA
        quote: >
          -
        description: | # this will include new lines to allow paragraphs
          -

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      -hobbies:
      Video games, hiking, baking

      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
